pypy tests fail with an SQLite error message on pypy
    django.db.utils.NotSupportedError: deterministic=True requires building _sqlite3 with SQLite 3.8.3 or higher