pypy tests fail with an SQLite error message on pypy (#1505)
django.db.utils.NotSupportedError: deterministic=True requires building _sqlite3 with SQLite 3.8.3 or higher